добавлена возможность подписываться и отписываться от встречи
anza-afk/tabletop-games-bboard pull request #28
Opened 2022-03-24 15:08 UTC by Varlok009

2022-03-24 18:22 UTC, Dirlandets requested changes
Молодец, но есть что поправить

2022-03-24 18:22 UTC, Dirlandets commented on webapp/users.py
> +            meet.wishing_to_play = meet.wishing_to_play + [user_id]
А зачем иф для одного и того же? Просто wishing должно быть сразу инициализироваться пустым списком а не нулём, тогда можно просто аппендить юзера.

2022-03-24 18:22 UTC, Dirlandets commented on webapp/__init__.py
>  from flask_migrate import Migrate
Кодить в __init__.py моветон

2022-03-24 18:22 UTC, Dirlandets commented on webapp/users.py
> +            meet.wishing_to_play = list(set(meet.wishing_to_play) - {user_id})
Лучше для мит реализовать метод add_user и delete_user тогда будет ооп

2022-03-24 18:24 UTC, anza-afk commented on webapp/__init__.py
>  from flask_migrate import Migrate
это из методички вроде, если ты про мигрейт

2022-03-24 19:01 UTC, Dirlandets commented on webapp/__init__.py
>  from flask_migrate import Migrate
Да я понимаю что в методичке

2022-03-25 14:27 UTC, Varlok009 commented on webapp/users.py
> +            meet.wishing_to_play = meet.wishing_to_play + [user_id]
С инитом списков при создании встречи конечно проще :)
через append изначально пробовал, но не добавляется юзер - не понял почему
пробовал так - (meet.wishing_to_play.append(user_id)) без присваивания естественно
по итогу работает только с явным присваиванием

2022-03-25 16:14 UTC, Varlok009 commented on webapp/users.py
> +            meet.wishing_to_play = list(set(meet.wishing_to_play) - {user_id})
Добавлено

2022-03-26 12:41 UTC, anza-afk approved these changes

2022-03-26 13:14 UTC, anza-afk approved these changes

2022-03-26 13:33 UTC, Dirlandets approved these changes

2022-03-26 13:34 UTC, merged