можно управлять участниками встречи, но почти без фронта
anza-afk/tabletop-games-bboard pull request #37
Opened 2022-03-30 17:48 UTC by Varlok009

Пока точно не мерджите, я еще фронт все таки накидаю

на странице редактирования встречи можно управлять участниками (да, эти уродские кнопки +/-)
при редактировании самой встречи все еще нужно указать время вручную (если вдруг нажмете туда)
для удобства тестирования можете взять юзера "botbot" - 12345 (у него есть и встречи созданные и на его встречи есть подписанные участники)

2022-03-31 08:38 UTC, Dirlandets requested changes

2022-03-31 08:38 UTC, Dirlandets commented on webapp/__init__.py
> +                meet = session.query(GameMeeting).filter(GameMeeting.id == buttons.current_meet.data).first()
Тут должен быть JOIN

https://www.tutorialspoint.com/sqlalchemy/sqlalchemy_orm_working_with_joins.htm

2022-03-31 08:38 UTC, Dirlandets commented on webapp/__init__.py
> +                meet = session.query(GameMeeting).filter(GameMeeting.id == buttons.current_meet.data).first()
Попробуй решить задачу тут джоином, вылядит как задача под него так как ниже ты по сути джоинишь MeetingUser.meeting_id == meet.id и MeetingUser.user_id == current_user.id

Отправляется куча запросов, а должен быть один

2022-03-31 08:38 UTC, Dirlandets commented on webapp/__init__.py
> +        meet_date = str(meeting_data.meeting_date_time).split()[0]
Посмотри как из DateTime достать дату и время, не нужно сплитить строики и вот это вот все

2022-03-31 08:38 UTC, Dirlandets commented on webapp/__init__.py
> +        meeting_data = join_meets(meet_id=session['current_meet'])
Все должно проходить в рамках одной сессии, у тебя методы на каждое двежение открывают новую сессию.

join_meets - название функции не очем не гвоорит, нет комментария что она делает. Бросайте эту фигню.

Сначала пишешь словами что функция делает и зачем. Потом код. Через неделю ты на нее будешь смотреть и непонимать что она делает.

2022-03-31 08:38 UTC, Dirlandets commented on webapp/__init__.py
> +                meeting = MeetingUser.get_meet(meeting_id, session)
Обычно принто сессию первым аргументом передавать потом уже остальное

2022-03-31 08:38 UTC, Dirlandets commented on webapp/users.py
>  def game_full_info(game_id):
Не открываем новые сессии в методах

2022-03-31 17:23 UTC, Varlok009 commented on webapp/__init__.py
> +                meet = session.query(GameMeeting).filter(GameMeeting.id == buttons.current_meet.data).first()
+

2022-03-31 17:25 UTC, Varlok009 commented on webapp/__init__.py
> +                meeting = MeetingUser.get_meet(meeting_id, session)
+

2022-04-01 12:48 UTC, Dirlandets approved these changes
молодец

2022-04-01 13:10 UTC, merged